version: "3"
services:
  song-mern:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    command: npm run dev
